# spring config
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

# rabbitmq config
rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest
  listener:
    acknowledge-mode: manual
messaging:
  comments:
    routing: post_queue
  likes:
    routing: like_queue

# common-core config
write:
  enabled: true