# base url
server:
  servlet:
    context-path: /post-service/api

# rabbitmq config
rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest
  listener:
    acknowledge-mode: manual
messaging:
  comments:
    routing: post_queue
  likes:
    routing: like_queue